// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SicData.Api.Data;

#nullable disable

namespace SicData.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904172518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SicData.Api.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line2");

                    b.Property<string>("AddressMatch")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_match");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("business_name");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_number");

                    b.Property<string>("CompanyStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_status");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_type");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("county");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dataset_id");

                    b.Property<string>("DateOfCreation")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_creation");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("fname");

                    b.Property<string>("NatureOfControl")
                        .HasColumnType("TEXT")
                        .HasColumnName("nature_of_control");

                    b.Property<string>("PersonWithSignificantControl")
                        .HasColumnType("TEXT")
                        .HasColumnName("person_with_significant_control");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("postcode");

                    b.Property<string>("SelectedPersonSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_person_source");

                    b.Property<string>("SelectedPscNatureOfControl")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_psc_nature_of_control");

                    b.Property<string>("SelectedPscShareTier")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_psc_share_tier");

                    b.Property<string>("Sic")
                        .HasColumnType("TEXT")
                        .HasColumnName("sic");

                    b.Property<string>("Sname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sname");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Town")
                        .HasColumnType("TEXT")
                        .HasColumnName("town");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT")
                        .HasColumnName("website");

                    b.Property<string>("WebsiteAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("website_address");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNumber");

                    b.HasIndex("County");

                    b.HasIndex("Postcode");

                    b.HasIndex("DatasetId", "County");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("SicData.Api.Domain.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Counties")
                        .HasColumnType("TEXT")
                        .HasColumnName("counties");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SicCodes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sic_codes");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file");

                    b.Property<int>("TotalCompanies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_companies");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("SicData.Api.Domain.DatasetAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CountyResolution")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("county_resolution");

                    b.Property<double>("DataQualityScore")
                        .HasColumnType("REAL")
                        .HasColumnName("data_quality_score");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dataset_id");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at");

                    b.Property<string>("MissingData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("missing_data");

                    b.Property<string>("RegionalDistribution")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("regional_distribution");

                    b.Property<int>("TotalCompanies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_companies");

                    b.Property<int>("UniqueCounties")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unique_counties");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId")
                        .IsUnique();

                    b.ToTable("dataset_analysis", (string)null);
                });

            modelBuilder.Entity("SicData.Api.Domain.Company", b =>
                {
                    b.HasOne("SicData.Api.Domain.Dataset", "Dataset")
                        .WithMany("Companies")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("SicData.Api.Domain.DatasetAnalysis", b =>
                {
                    b.HasOne("SicData.Api.Domain.Dataset", "Dataset")
                        .WithOne("Analysis")
                        .HasForeignKey("SicData.Api.Domain.DatasetAnalysis", "DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("SicData.Api.Domain.Dataset", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
